sitegroup: zee

deploy_tasks:
  development:
    after_deploy:
      - drush -y updb --cache-clear=0
      - drush -y cr
  production:
    after_deploy:
      - drush -y updb --cache-clear=0
      - drush -y cr

shared:
  production:
    - src: files
      dst: sites/default/files
